import datetime
import sys,os

from common.readconfig import ReadConfig

sys.path.append(os.path.abspath(os.path.dirname(__file__)).split("/flash/")[0]+"/flash")
import allure
from assertpy import assert_that
import requests
import logging
import ast
import json
import time
import pytest
from common.base import BaseTestCase
from utils.redisbase import RedisBase
from jsonschema import validate
                
logging.basicConfig(level=logging.INFO)


@allure.feature('bi网点经理工单列表页面')
class Test_ms_work_order_list_page(object):
    def setup_class(self):
        self.redisObj = RedisBase()
        self.runenv_py = self.redisObj.get("runenv_py")
        self.cookier = self.redisObj.get("indentifi_manager_PHPSESSID")
        self.host = ReadConfig().get_config(self.runenv_py, "fbi_host_domain")
        # self.iframe_0 = self.redisObj.get("test_1_1_iframe_0")
        self.pno = self.redisObj.get('courier_write_order_0_0_0_["data"]["parcel_info"]["pno"]')
        self.pno1 = self.redisObj.get('courier_write_order_1_0_0_["data"]["parcel_info"]["pno"]')
        self.pno2 = self.redisObj.get('courier_write_order_2_0_0_["data"]["parcel_info"]["pno"]')
        self.pno3 = self.redisObj.get('courier_write_order_3_0_0_["data"]["parcel_info"]["pno"]')
        self.pno4 = self.redisObj.get('courier_write_order_4_0_0_["data"]["parcel_info"]["pno"]')
        self.pno5 = self.redisObj.get('courier_write_order_5_0_0_["data"]["parcel_info"]["pno"]')
        self.pno6 = self.redisObj.get('courier_write_order_6_0_0_["data"]["parcel_info"]["pno"]')
        self.pno6 = self.redisObj.get('courier_write_order_6_0_0_["data"]["parcel_info"]["pno"]')
        self.iframe_0 = self.redisObj.get("test_1_1_iframe_0")
        self.iframe_2 = self.redisObj.get("test_1_1_iframe_2")
        self.iframe_3 = self.redisObj.get("test_1_1_iframe_3")
        self.iframe_1 = self.redisObj.get("test_1_1_iframe_1")

    @pytest.mark.run(order=103)
    def test_test_ms_work_order_list_page(self):

        url = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url1 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno1 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url2 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno2 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url3 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno3 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url4 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno4 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url5 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno5 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'
        url6 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]=' + self.pno6 + '&search[regex]=false&f=my_dealing&date='+str(datetime.date.today()) + " 00:00:00" +" - " + str(datetime.date.today()) + " 23:59:59" + '&staff_id=&status=0'




        # url = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url1 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno1+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url2 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno2+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url3 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno3+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url4 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno4+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url5 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno5+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"
        # url6 = self.host + 'workorder/mydealing_ajax?draw=1&columns[0][data]=speed_level&columns[0][name]=&columns[0][searchable]=false&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=status&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=title&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=order_type&columns[3][name]=&columns[3][searchable]=false&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=reply_time&columns[4][name]=&columns[4][searchable]=false&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=&columns[5][searchable]=false&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=reminder_pno_created_at&columns[6][name]=&columns[6][searchable]=false&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=reply_staff_info_name&columns[7][name]=&columns[7][searchable]=false&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=latest_deal_at&columns[8][name]=&columns[8][searchable]=false&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=staff_info_id&columns[9][name]=&columns[9][searchable]=false&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=worder_staff_store_name&columns[10][name]=&columns[10][searchable]=false&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&start=0&length=100&search[value]='+self.pno6+'&search[regex]=false&f=my_dealing&date='+ str(datetime.date.today()) + " 00:00:00" + " - " + str(datetime.date.today()) + " 23:59:59&staff_id=&status=0"



        headers = {
            "Accept": "application/json, text/plain, */*",
            "Accept-Encoding": "gzip, deflate",
            "Accept-Language": "zh-CN",
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Cookie": self.cookier

        }


        resp = requests.post(url=url, headers=headers, verify=False)
        resp1 = requests.post(url=url1,headers=headers,verify=False)
        resp2 = requests.post(url=url2,headers=headers,verify=False)
        resp3 = requests.post(url=url3,headers=headers,verify=False)
        resp4 = requests.post(url=url4,headers=headers,verify=False)
        resp5 = requests.post(url=url5,headers=headers,verify=False)
        resp6 = requests.post(url=url6,headers=headers,verify=False)

        logging.info("请求头是：")
        logging.info(headers)
        logging.info("请求URL是：")
        logging.info(url)

        logging.info("响应结果日志信息：")
        logging.info(resp.json())
        RedisBase().set('ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp.status_code).is_equal_to(200)
        assert_that(resp.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url1)


        RedisBase().set('1ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp1.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('1ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp1.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp1.status_code).is_equal_to(200)
        assert_that(resp1.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url2)


        RedisBase().set('2ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp2.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('2ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp2.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp2.status_code).is_equal_to(200)
        assert_that(resp2.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url3)


        RedisBase().set('3ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp3.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('3ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp3.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp3.status_code).is_equal_to(200)
        assert_that(resp3.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url4)


        RedisBase().set('4ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp4.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('4ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp4.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp4.status_code).is_equal_to(200)
        assert_that(resp4.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url5)


        RedisBase().set('5ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp5.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('5ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp5.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp5.status_code).is_equal_to(200)
        assert_that(resp5.json()["code"]).is_equal_to(1)
        logging.info("请求URL是：")
        logging.info(url6)

        RedisBase().set('6ms_work_order_list_page_["data"]["DataList"][0]["pnos"]', resp6.json()["data"]["DataList"][0]["pnos"],ex=6000)
        RedisBase().set('6ms_work_order_list_page_["data"]["DataList"][0]["order_id"]',resp6.json()["data"]["DataList"][0]["order_id"], ex=6000)
        assert_that(resp6.status_code).is_equal_to(200)
        assert_that(resp6.json()["code"]).is_equal_to(1)


