# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

    def teardown_method(self, method):
        self.driver.implicitly_wait(10)
        self.driver.quit()

    def test_testsearch(self):
        self.driver.get("http://www.baidu.com")
        self.driver.maximize_window()
        element = (By.ID, "s-usersetting-top")
        els = Select(element)
        print(els)
        print(els.select_by_index(0))
        self.driver.find_element(By.ID, "s-usersetting-top").click()
