# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestDefaultSuite:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.driver.get("https://testerhome.com/")
        self.driver.implicitly_wait(5)  # 隐式等待

    def teardown_method(self, method):
        pass
        # self.driver.quit()

    def test_testsearch(self):
        element = (By.CSS_SELECTOR, ".col-xs-12:nth-child(1) .team-name")
        element1 = (By.CSS_SELECTOR, ".topic-21567 .title > a")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(1) > li:nth-child(4) > a").click()
        WebDriverWait(self.driver, 10).until(
            expected_conditions.element_to_be_clickable(element))  # 显式等待
        self.driver.find_element(*element).click()
        WebDriverWait(self.driver, 5).until(
            expected_conditions.element_to_be_clickable(element1))  # 显式等待
        self.driver.find_element(*element1).click()
