import redis

r = redis.StrictRedis(host="localhost", port=6379, db=15, password="flash123", decode_responses="UTF-8")
# r.set("name", "电话", ex=10, xx=True)
# r.set("address", "beijing", px=2000, nx=True)
# r.append("age", 19)
# print(r.get("name"))
# print(r.get("address"))
# print(r.get("age"))
# r.mset({"height": 100, "weight": 200, "length": 300})
# print(r.mget("height"))
# r.set("add", 10)
# print(type(r.get("add")))
# r.incr("add", amount=1)
# r.incr("add", amount=1)
# print(r.get("add"))
# print(r.keys("*"))
# print(type(r.get("length")))
r.lpush("list1", 1)
print(r.lrange("list1", 0, 0))
print(r.keys("a*"))
