# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
from httprunner import HttpRunner, TConfig, TStep


class TestCaseDemoTestcase(HttpRunner):
    config = TConfig(
        **{
            "name": "demo testcase",
            "variables": {
                "device_sn": "ABC",
                "username": "${ENV(USERNAME)}",
                "password": "${ENV(PASSWORD)}",
            },
            "base_url": "http://127.0.0.1:5000",
            "path": r"D:\MyProjects\test-demo\testcases\demo_testcase_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "demo step 1",
                "api": "path/to/api1.yml",
                "variables": {"user_agent": "iOS/10.3", "device_sn": "$device_sn"},
                "extract": {"token": "content.token"},
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "demo step 2",
                "api": "path/to/api2.yml",
                "variables": {"token": "$token"},
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcase().test_start()
